import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { ThemeProvider } from "@/components/theme-provider"
import { ModeToggle } from '@/components/toggleTheme'
import AvatarComponent from '@/components/Avatar'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LanguageLearningFromSubs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <nav className="h-16 px-4 flex justify-between border-b shadow-md">
            <div className="flex items-center">
              <ModeToggle />
              <NavBar />
            </div>
            <AvatarComponent />
          </nav>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
